# Settings
kotlin.incremental.multiplatform=true
kotlin.incremental.usePreciseJavaTracking=true
kotlin.code.style=official
kotlin.compiler.effectSystemEnabled=true
kotlin.compiler.newInferenceEnabled=true
kotlin.mpp.stability.nowarn=true
kotlin.incremental.js.ir=true
kotlin.incremental.useClassPathSnapshot=true
kotlin.build.report.output=file
kotlin.incremental.native=true

org.gradle.cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true





SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true